src/Entity/User.php
<?php

namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Table("utilisateur")
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Length(
     *      min = 2,
     *      max = 26,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     */
    private $first_name;

    /**
     * @ORM\Column(type="string")
     * @Assert\Length(
     *      min = 2,
     *      max = 26,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     *
     */
    private $last_name;


     /**
     * @ORM\Column(type="string")
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email.",
     *     checkMX = true
     * )
     */


      /**
     * @ORM\Column(type="integer")
     *  @Assert\Length(
     *
     *      max = 8,
     *      min = 8,
     *      exactMessage = "Your number must have {{ limit }} digits"
     * )
     */
    private $number;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;
    /**
     * @ORM\Column(type="datetime")
     */
    private $created_date_user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $last_updated_user;

    // /**
    //  * @Recaptcha\IsTrue
    //  */
    // public $recaptcha;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default" : 0})
     */
    private $blocked;

    
     /**
     * @ORM\OneToMany(targetEntity=Commandes::class, mappedBy="utilisateur")
     *@ORM\JoinColumn(nullable=true)
     */
    private $commandes;


    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getCreatedDateUser(): ?\DateTimeInterface
    {
        return $this->created_date_user;
    }

    public function setCreatedDateUser(\DateTimeInterface $created_date_user): self
    {
        $this->created_date_user = $created_date_user;

        return $this;
    }

    public function getLastUpdatedUser(): ?\DateTimeInterface
    {
        return $this->last_updated_user;
    }

    public function setLastUpdatedUser(\DateTimeInterface $last_updated_user): self
    {
        $this->last_updated_user = $last_updated_user;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getBlocked(): ?bool
    {
        return $this->blocked;
    }

    public function setBlocked(?bool $blocked): self
    {
        $this->blocked = $blocked;

        return $this;
    }


    public function getCommandes()
    {
        return $this->commandes;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('password', PasswordType::class, [
                // instead of being set onto the object directly,
                // this is read and encoded in the controller
                'mapped' => false,
            ])
            ->add('first_name')
            ->add('last_name')
            ->add('number')
            ->add('birthday')
            ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
	<button class="btn btn-sm btn-danger">Delete</button>
</form>

templates/user/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{{ form_start(form)}}
{{ form_widget(form) }}
<button class="btn btn-sm btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% block title %}Edit User
{% endblock %}

{% block content %}

	{{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

	<a href="{{ path('app_user_index') }}" class="btn btn-sm btn-primary">back to list</a>


	{{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% block title %}User index
{% endblock %}

{% block content %}

	<table class="table">
		<thead>
			<tr>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Email</th>
				<th>Number</th>
				<th>Role</th>
				<th>Birthday</th>
				<th>Profile</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for user in users %}
				<tr>
					<td>{{ user.firstName }}</td>
					<td>{{ user.lastName }}</td>
					<td>{{ user.email }}</td>
					<td>{{ user.number }}</td>
					<td>{{ user.roles ? user.roles|json_encode : '' }}</td>
					<td>{{ user.birthday ? user.birthday|date('Y-m-d') : '' }}</td>
					<td>
						<img src="{{ qr_code_url('http://192.168.1.9:8000/profile/' ~ user.id) }}" width="75px"/>


					</td>
					<td>
						<a href="{{ path('app_user_show', {'id': user.id}) }}" class="btn btn-sm btn-primary">Show</a>
						<a href="{{ path('app_user_edit', {'id': user.id}) }}" class="btn btn-sm btn-warning">Edit</a>
						{% if user.blocked %}
							<a href="{{ path('app_user_unblock', {'id': user.id}) }}" class="btn btn-sm btn-success">Unblock</a>

						{% else %}
							<a href="{{ path('app_user_block', {'id': user.id}) }}" class="btn btn-sm btn-danger">Block</a>
						{% endif %}
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="12">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_user_new') }}" class="btn btn-sm btn-success">Create new user</a>

{% endblock %}

templates/user/new.html.twig
{% block title %}New User
{% endblock %}

{% block content %}
	<h1>Create new User</h1>

	{{ include('user/_form.html.twig') }}

	<a href="{{ path('app_user_index') }}" class="btn btn-sm btn-primary">back to list</a>

{% endblock %}

templates/user/show.html.twig
{% extends 'front.html.twig' %}

{% block title %}User
{% endblock %}

{% block content %}
	<h1>User</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>First Name</th>
				<td>{{ user.firstName }}</td>
			</tr>
			<tr>
				<th>Last Name</th>
				<td>{{ user.lastName }}</td>
			</tr>
			<tr>
				<th>Email</th>
				<td>{{ user.email }}</td>
			</tr>
			<tr>
				<th>Number</th>
				<td>{{ user.number }}</td>
			</tr>
			<tr>
				<th>Role</th>
				<td>{{ user.roles ? user.roles|json_encode : '' }}</td>

			</tr>
			<tr>
				<th>Birthday</th>
				<td>{{ user.birthday ? user.birthday|date('Y-m-d') : '' }}</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('app_user_index') }}" class="btn btn-sm btn-primary">back to list</a>

	<a href="{{ path('app_user_edit', {'id': user.id}) }}" class="btn btn-sm btn-warning">edit</a>


	{{ include('user/_delete_form.html.twig') }}
{% endblock %}